<?php

namespace AppBundle\Repository;

/**
 * GlobalSubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalSubscriberRepository extends \Doctrine\ORM\EntityRepository
{
}
