<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use AppBundle\Util\Page;
use AppBundle\Util\Pageable;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser(User $user, Pageable $pageable) : Page{
        $qb = $this->createQueryBuilder('i');
        $qb
            ->where('i.owner = :user')
            ->setParameter('user', $user)
            ->orderBy('i.id', 'DESC');
        return new Page($qb, $pageable);
    }
}
