<?php

namespace AppBundle\Repository;

/**
 * LikeReactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeReactionRepository extends \Doctrine\ORM\EntityRepository
{
}
