<?php

namespace AppBundle\Repository;

use AppBundle\Util\Page;
use AppBundle\Util\Pageable;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPage(Pageable $pageable) : Page{
        return new Page($this->createQueryBuilder('l')->orderBy('l.id', 'DESC'), $pageable);
    }
}
