<?php

namespace AppBundle\Repository;

use AppBundle\Util\Page;
use AppBundle\Util\Pageable;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPage(Pageable $pageable) : Page{
        return new Page($this->createQueryBuilder('q')->orderBy('q.id', 'DESC'), $pageable);
    }
}
