<?php

namespace AppBundle\Repository;

use Doctrine\ORM;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class QuoteRepository extends \Doctrine\ORM\EntityRepository
{

}
